apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: symcloudinaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: kulbhushanmayer/thinknyx_voting_app:1.0
        name: vote
        command:
        - sh
        - -c
        - "gunicorn app:app -b 0.0.0.0:80 --log-file - --access-logfile - --workers 4 --keep-alive 0"
        ports:
        - containerPort: 80
          name: vote
        envFrom:
        - configMapRef:
            name: db-details
        resources:
          limits:
            memory: 250Mi
            cpu: 250m
        
