apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: symcloudinaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: kulbhushanmayer/voting_app:worker_1.0
        name: worker
        envFrom:
        - configMapRef:
            name: db-details
        - secretRef:
            name: db-password
        resources:
          limits:
            memory: 500Mi
            cpu: 250m

