apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    type: backend
spec:
  capacity: 
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  nfs:
    server: fs-0efcaa4c3832e6f53.efs.us-east-2.amazonaws.com
    path: /
  mountOptions:
  - hard
  - nfsvers=4.1
  storageClassName: manual
