apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: symcloudinaction
  labels:
    type: backend
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: manual

